export const APP_CONSTANTS = {
  DEFAULT_API_PREFIX: 'api/v1',
  DEFAULT_PORT: 3001,
  PASSWORD_MIN_LENGTH: 8,
  JWT_ACCESS_EXPIRES_IN: '15m',
  JWT_REFRESH_EXPIRES_IN: '7d',
  DEFAULT_PAGE_SIZE: 25,
  MAX_PAGE_SIZE: 100,
} as const;
